---
title: "Codebook"
author: "Ross"
date: "8/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Explanation of Variable Names

This data set was obtained from mobile phone embedded (1) accelerometer and (2) gyroscopic measurements from a group of 30 subjects (ID = 1-30) perfoming 6 different activities. (1 = walking, 2 = walking upstairs, 3 = walking downstairs, 4 = sitting, 5 = standing, 6 = laying)

These measurements were recorded over time (t) in 3 different dimensions (XYZ).
Thus tAccX = accelerometer reading over time in the X axis. 

The accelerometer readings were then filtered and separated into body acceleration and gravity acceleration (tBodyAcc-XYZ and tGravityAcc-XYZ).

Both accelerometer and gyroscopic measurements were also derived to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ).

The magnitude of these signals (inlcuding derived Jerk) were also then calculated (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag).

Following this a Fast Fourier Transform was applied to some of these parameters and this is denoted by a preceding "f".

A further set of variables were then estimated including

mean(): Mean value
std(): Standard deviation
mad(): Median absolute deviation 
max(): Largest value in array
min(): Smallest value in array
sma(): Signal magnitude area
energy(): Energy measure. Sum of the squares divided by the number of values. 
iqr(): Interquartile range 
entropy(): Signal entropy
arCoeff(): Autorregresion coefficients with Burg order equal to 4
correlation(): correlation coefficient between two signals
maxInds(): index of the frequency component with largest magnitude
meanFreq(): Weighted average of the frequency components to obtain a mean frequency
skewness(): skewness of the frequency domain signal 
kurtosis(): kurtosis of the frequency domain signal 
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
angle(): Angle between to vectors.

These are denoted at the end of the variables

There are a total of 561 variables

